spring: 
  datasource:
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
    password: jaggu444
    url: jdbc:sqlserver://localhost:1433;encrypt=true;trustServerCertificate=true;databaseName=java_prod
    username: jagadeesh
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServer2012Dialect
        format_sql: true
    show-sql: true 
  boot:
    admin:
      client:
        url:
        - "http://localhost:9090"
# This is about Actuator        
management:
  endpoints:
    web:
      exposure:
        exclude:    
accounts:
  message: "Welcome to PROD configuration of EazyBank Accounts related local APIs "
  contactDetails:
    name: "PROD John Doe - Developer"
    email: "prodjohn@eazybank.com"
  onCallSupport:
    - (555) 555-1234
    - (555) 523-1345"    
 
