spring:
  datasource:
    url: jdbc:mysql://localhost:3306/eazybank_dev
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
    show-sql: true 
accounts:
  message: "Welcome to DEV configuration of EazyBank Accounts related local APIs "
  contactDetails:
    name: "Dev John Doe - Developer"
    email: "devjohn@eazybank.com"
  onCallSupport:
    - (555) 555-1234
    - (555) 523-1345"    
  
  



