server:
  port: 8081

spring:
  application:
    name: accounts   # make sure this is correct

  datasource:
    url: jdbc:mysql://localhost:3306/eazybytes
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  cloud:
    openfeign:
      circuitbreaker:
        enabled: true   # 🔥 MUST for fallback to work
      client:
        config:
          default:
            connectTimeout: 2000   # 2 seconds
            readTimeout: 2000      # 2 seconds

resilience4j:
  circuitbreaker:
    configs:
      default:
        slidingWindowSize: 10
        permittedNumberOfCallsInHalfOpenState: 2
        failureRateThreshold: 50
        waitDurationInOpenState: 10s

    instances:
      loans:
        baseConfig: default   # must match Feign client name
      cards:
        baseConfig: default   # optional (since you use cards also)

  timelimiter:
    instances:
      loans:
        timeoutDuration: 2s   # 🔥 for debug pause testing
      cards:
        timeoutDuration: 2s   # optional

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      access: UNRESTRICTED

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
