spring:
  
  datasource:
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
    password: jaggu444
    url: jdbc:sqlserver://localhost:1433;encrypt=true;trustServerCertificate=true;databaseName=java_test
    username: jagadeesh
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServer2012Dialect
        format_sql: true
    show-sql: true 
 
  
  
