server:
  port: 8081

spring:
  config:
    import: "optional:configserver:http://localhost:8500"


  datasource:
    url: jdbc:mysql://localhost:3306/eazybytes
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
