 

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/accounts_dev
    username: root
    password: root
   
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
    show-sql: true 
    
cards:
  message: "Welcome to DEV configuration of EazyBank Cards related local APIs "
  contactDetails:
    name: "Dev John Doe - Developer"
    email: "devjohn@eazybank.com"
  onCallSupport:
    - (555) 555-1234
    - (555) 523-1345"        
    
    
  
  

