 

spring:
  datasource:
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
    password: jaggu444
    url: jdbc:sqlserver://localhost:1433;encrypt=true;trustServerCertificate=true;databaseName=java_prod
    username: jagadeesh
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServer2012Dialect
        format_sql: true
    show-sql: true  
  #This is about spring admin details      
  boot:
    admin:
      client:
        url:
        - "http://localhost:9090/"    

#This is about  actuator 
management:
  endpoints:
    web:
      exposure:
        include: "*"
        
        

       
server:
  port: 8082
  error:
    include-message: always
    include-stacktrace: never
    
cards:
  message: "Welcome to PROD configuration of EazyBank Cards related local APIs "
  contactDetails:
    name: "PROD John Doe - Developer"
    email: "prodjohn@eazybank.com"
  onCallSupport:
    - (555) 555-1234
    - (555) 523-1345"        
    
    
  
  
