spring:
  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: true #discovery locator enable this is used for when ever a request come from the outside it should be register
              lowerCaseServiceId: true #This is for the service url name should be in lowercase

server:
  port: 8505

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    gateway:
      access: UNRESTRICTED
  
