server:
  port: 8083

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/eazybytes
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
management:
  endpoints:
    web:
      exposure:
        include:
          - "*"
  endpoint:
    shutdown:
      #UNRESTRICTED means when ever we try to call actuator/shutdown it will automatically stop the server
      #none means when ever we try to call actuator/shutdown it will not allow to stop the server
      # READ_ONLY when ever we try to call actuator/shutdown it will Allow GET but not shutdown
      access: UNRESTRICTED       
eureka:
  instance:
  # below ip address is true because in localhost we are not using any dns right if we add this it will generate random ip address
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka           
